config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/about', to: 'static_pages#about'
  post '/pokemon_battles/attack',  to: 'pokemon_battles#attack'
  get  '/pokemon_battles/history', to: 'pokemon_battles#history'
  resources :pokedexes#, only: [:index, :show]
  resources :pokemons
  resources :pokemon_battles
  resources :skills
end

app/models/pokedex.rb
class Pokedex < ApplicationRecord
  belongs_to :type
  has_many :pokemon_players
end

app/controllers/pokedexes_controller.rb
class PokedexesController < ApplicationController
  def index
    @pokedexes = Pokedex.page(params[:page]).per(15).order(:id)
  end

  def show
    @pokedex = Pokedex.find(params[:id])
  end

  def new
    @pokedex = Pokedex.new
    @types = Type.all
  end

  def create
    pokedex = Pokedex.new(pokedex_params)
    if pokedex.save
      flash[:success] = "Pokedex #{pokedex.name} created!"
      redirect_to pokedexes_url
    else
      render 'new'
    end
  end

  def edit
    @pokedex = Pokedex.find(params[:id])
    @types = Type.all
  end

  def update
    @pokedex = Pokedex.find(params[:id])
    if @pokedex.update(pokedex_params)
      flash[:success] = 'Pokedex updated.'
      redirect_to pokedexes_url
    else
      render 'edit'
    end
  end

  def destroy
    @pokedex = Pokedex.find(params[:id])
    @pokedex.destroy
    flash[:success] = 'Pokedex deleted.'
    redirect_to pokedexes_url
  end

  private

    def pokedex_params
      params.require(:pokedex).permit(:name, :image_url, :base_hp, :base_attack, :base_defense, :base_speed, :type_id)
    end

end

app/helpers/pokedexes_helper.rb
module PokedexesHelper
end

app/views/pokedexes/_form.html.erb
<div class="row d-flex justify-content-center">
    <div class="col-md-6">
        <div class="mb-5">
            <label for="pokedex_name" class="form-label"><h4>Name</h4></label>
            <input type="text" class="form-control" id="pokedex_name" name="pokedex[name]" value="<%= @pokedex.name %>" placeholder="Pokedex name" required>
        </div>
        <div class="mb-5">
            <label for="pokedex_image_url" class="form-label"><h4>Image URL</h4></label>
            <input type="text" class="form-control" id="pokedex_image_url" name="pokedex[image_url]" value="<%= @pokedex.image_url %>" placeholder="Image URL" required>
        </div>
        <div class="mb-5">
            <label for="pokedex_base_hp" class="form-label"><h4>Base HP</h4></label>
            <input type="text" class="form-control" id="pokedex_base_hp" name="pokedex[base_hp]" value="<%= @pokedex.base_hp %>" placeholder="Base HP" required>
        </div>
    </div>
    <div class="col-md-6">
        <div class="mb-5">
            <label for="pokedex_base_attack" class="form-label"><h4>Base Attack</h4></label>
            <input type="text" class="form-control" id="pokedex_base_attack" name="pokedex[base_attack]" value="<%= @pokedex.base_attack %>" placeholder="Base Attack" required>
        </div>
        <div class="mb-5">
            <label for="pokedex_base_defense" class="form-label"><h4>Base Defense</h4></label>
            <input type="text" class="form-control" id="pokedex_base_defense" name="pokedex[base_defense]" value="<%= @pokedex.base_defense %>" placeholder="Base Defense" required>
        </div>
        <div class="mb-5">
            <label for="pokedex_base_speed" class="form-label"><h4>Base Speed</h4></label>
            <input type="text" class="form-control" id="pokedex_base_speed" name="pokedex[base_speed]" value="<%= @pokedex.base_speed %>" placeholder="Base Speed" required>
        </div>
    </div>
    <div class="col-md-3">
        <div class="mb-5">
            <h4>Element Type</h4>
            <select id="type-select" class="form-select text-center" name="pokedex[type_id]" aria-label="Default select example">
                <option selected>Choose element type</option>
                <% @types.each do |type| %>
                    <option value="<%= type.id %>"><%= type.name %></option>
                <% end %>
            </select>
        </div>
    </div>
</div>

app/views/pokedexes/edit.html.erb
<h1>Edit Pokedex</h1>
<form action="<%= pokedex_path(@pokedex) %>" accept-charset="UTF-8" method="post" class="form text-dark">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <input type="hidden" name="_method" value="patch">

    <%= render 'form' %>
    
    <button type="submit" class="btn btn-warning">UPDATE</button>
</form>

app/views/pokedexes/index.html.erb
<h1>List Pokedex</h1>

<p class="my-4">
  <%= link_to 'Create Pokedex', new_pokedex_path, class: 'btn btn-warning' %> 
</p>

<table class="table table-warning table-striped align-middle table-bordered">

  <thead>
    <tr>
      <th>#</th>
      <th>Image</th>
      <th>Name</th>
      <th>Type</th>
      <th>Base HP</th>
      <th>Base Attack</th>
      <th>Base Defense</th>
      <th>Base Speed</th>
      <th>Detail</th>
    </tr>
  </thead>
  
  <tbody>
    <% @pokedexes.each do |pokedex| %>
      <tr>
        <td><%= pokedex.id %></td>
        <td><img src="<%= pokedex.image_url %>" alt="image" class="image-pokedex__list"></td>
        <td><%= pokedex.name %></td>
        <td class="text-uppercase pt-3">
          <% if pokedex.type.name == "Grass" %>
            <p class="badge bg-grass"><%= pokedex.type.name %></p>
          <% elsif pokedex.type.name == "Fire" %>
            <p class="badge bg-fire"><%= pokedex.type.name %></p>
          <% elsif pokedex.type.name == "Water" %>
            <p class="badge bg-water"><%= pokedex.type.name %></p>
          <% elsif pokedex.type.name == "Normal" %>
            <p class="badge bg-normal"><%= pokedex.type.name %></p>
          <% elsif pokedex.type.name == "Electric" %>
            <p class="badge bg-electric"><%= pokedex.type.name %></p>
          <% elsif pokedex.type.name == "Bug" %>
            <p class="badge bg-bug"><%= pokedex.type.name %></p>
          <% elsif pokedex.type.name == "Fighting" %>
            <p class="badge bg-fighting"><%= pokedex.type.name %></p>
          <% elsif pokedex.type.name == "Poison" %>
            <p class="badge bg-poison"><%= pokedex.type.name %></p>
          <% elsif pokedex.type.name == "Flying" %>
            <p class="badge bg-flying"><%= pokedex.type.name %></p>
          <% elsif pokedex.type.name == "Ice" %>
            <p class="badge bg-ice"><%= pokedex.type.name %></p>
          <% elsif pokedex.type.name == "Ground" %>
            <p class="badge bg-ground"><%= pokedex.type.name %></p>
          <% elsif pokedex.type.name == "Psychic" %>
            <p class="badge bg-psychic"><%= pokedex.type.name %></p>
          <% elsif pokedex.type.name == "Rock" %>
            <p class="badge bg-rock"><%= pokedex.type.name %></p>
          <% elsif pokedex.type.name == "Ghost" %>
            <p class="badge bg-ghost"><%= pokedex.type.name %></p>
          <% elsif pokedex.type.name == "Dragon" %>
            <p class="badge bg-dragon"><%= pokedex.type.name %></p>
          <% elsif pokedex.type.name == "Fairy" %>
            <p class="badge bg-fairy"><%= pokedex.type.name %></p>
          <% else %>
            <%= pokedex.type.name %>
          <% end %>
        </td>
        <td><%= pokedex.base_hp %></td>
        <td><%= pokedex.base_attack %></td>
        <td><%= pokedex.base_defense %></td>
        <td><%= pokedex.base_speed %></td>
        <td>
          <%= link_to 'Edit', edit_pokedex_path(pokedex), class: 'btn btn-success' %>
          <%= link_to 'Show', pokedex_path(pokedex), class: 'btn-show' %>
        </td>
      </tr>
    <% end %>
  </tbody>
  
</table>

<div class="d-flex justify-content-center my-4">
  <%= paginate @pokedexes %>
</div>

app/views/pokedexes/new.html.erb
<h1>New Pokedex</h1>
<form action="<%= pokedexes_path %>" accept-charset="UTF-8" method="post" class="form text-dark">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    
    <%= render 'form' %>
    
    <button type="submit" class="btn btn-warning">SUBMIT</button>
</form>

app/views/pokedexes/show.html.erb
<h1 class="mb-4">Pokedex</h1>
<div class="d-flex justify-content-center">
    <div class="card" style="width: 44rem;">
        <div class="card-body">
            <div class="row d-flex justify-content-center align-items-center">
                <div class="col-md-4">
                    <img src="<%= @pokedex.image_url %>" alt="<%= @pokedex.name %>" class="image-pokedex__show">
                    <h3><%= @pokedex.name %></h3>
                    <h5 class="text-uppercase">
                        <% if @pokedex.type.name == "Grass" %>
                            <p class="badge bg-grass"><%= @pokedex.type.name %></p>
                        <% elsif @pokedex.type.name == "Fire" %>
                            <p class="badge bg-fire"><%= @pokedex.type.name %></p>
                        <% elsif @pokedex.type.name == "Water" %>
                            <p class="badge bg-water"><%= @pokedex.type.name %></p>
                        <% elsif @pokedex.type.name == "Normal" %>
                            <p class="badge bg-normal"><%= @pokedex.type.name %></p>
                        <% elsif @pokedex.type.name == "Electric" %>
                            <p class="badge bg-electric"><%= @pokedex.type.name %></p>
                        <% elsif @pokedex.type.name == "Bug" %>
                            <p class="badge bg-bug"><%= @pokedex.type.name %></p>
                        <% elsif @pokedex.type.name == "Fighting" %>
                            <p class="badge bg-fighting"><%= @pokedex.type.name %></p>
                        <% elsif @pokedex.type.name == "Poison" %>
                            <p class="badge bg-poison"><%= @pokedex.type.name %></p>
                        <% elsif @pokedex.type.name == "Flying" %>
                            <p class="badge bg-flying"><%= @pokedex.type.name %></p>
                        <% elsif @pokedex.type.name == "Ice" %>
                            <p class="badge bg-ice"><%= @pokedex.type.name %></p>
                        <% elsif @pokedex.type.name == "Ground" %>
                            <p class="badge bg-ground"><%= @pokedex.type.name %></p>
                        <% elsif @pokedex.type.name == "Psychic" %>
                            <p class="badge bg-psychic"><%= @pokedex.type.name %></p>
                        <% elsif @pokedex.type.name == "Rock" %>
                            <p class="badge bg-rock"><%= @pokedex.type.name %></p>
                        <% elsif @pokedex.type.name == "Ghost" %>
                            <p class="badge bg-ghost"><%= @pokedex.type.name %></p>
                        <% elsif @pokedex.type.name == "Dragon" %>
                            <p class="badge bg-dragon"><%= @pokedex.type.name %></p>
                        <% elsif @pokedex.type.name == "Fairy" %>
                            <p class="badge bg-fairy"><%= @pokedex.type.name %></p>
                        <% else %>
                            <%= @pokedex.type.name %>
                        <% end %>
                    </h5>
                </div>
                <div class="col-md-6">
                    <p>Base HP: <%= @pokedex.base_hp %></p>
                    <p>Base Attack: <%= @pokedex.base_attack %></p>
                    <p>Base Defense: <%= @pokedex.base_defense %></p>
                    <p>Base Speed: <%= @pokedex.base_speed %></p>
                </div>
            </div>
            <%# link_to 'Edit', edit_pokedex_path(@pokedex), class: 'btn btn-success' %>
            <%# link_to 'Delete', pokedex_path(@pokedex), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </div>
    </div>
</div>