config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/about', to: 'static_pages#about'
  post '/pokemon_battles/attack',  to: 'pokemon_battles#attack'
  get  '/pokemon_battles/history', to: 'pokemon_battles#history'
  resources :pokedexes#, only: [:index, :show]
  resources :pokemons
  resources :pokemon_battles
  resources :skills
end

app/models/pokemon_battle.rb
class PokemonBattle < ApplicationRecord
  belongs_to :pokemon1, class_name: 'PokemonPlayer',
												foreign_key: 'pokemon1_id'
	belongs_to :pokemon2, class_name: 'PokemonPlayer',
												foreign_key: 'pokemon2_id'
	belongs_to :pokemon_winner, class_name: 'PokemonPlayer',
												foreign_key: 'pokemon_winner_id',
												optional: true
	belongs_to :pokemon_loser, class_name: 'PokemonPlayer',
												foreign_key: 'pokemon_loser_id',
												optional: true

  default_scope -> { order(created_at: :desc) }

  validates :time, presence: true
  validates :status, presence: true
  validates :pokemon1_id, presence: true
	validates :pokemon2_id, presence: true
	validates :current_turn, presence: true
end

app/controllers/pokemon_battles_controller.rb
class PokemonBattlesController < ApplicationController
  include PokemonBattlesHelper

  def index
    @pokemon_battles = PokemonBattle.page(params[:page]).per(15)
  end

  def new
    @pokemons = PokemonPlayer.all
  end

  def create
    # Mendapatkan nilai dari params
    pokemon_1_info = params[:pokemon_1][:pokemon_player_id].split('-')
    pokemon_2_info = params[:pokemon_2][:pokemon_player_id].split('-')

    pokemon_1_id = pokemon_1_info[0].to_i
    pokemon_1_max_hp = pokemon_1_info[1].to_i

    pokemon_2_id = pokemon_2_info[0].to_i
    pokemon_2_max_hp = pokemon_2_info[1].to_i

    pokemon_battle = PokemonBattle.new(
      time: DateTime.now,
      status: "ON BATTLE",
      current_turn: 1,
      pokemon1_id: pokemon_1_id,
      pokemon2_id: pokemon_2_id,
      pokemon1_max_hp: pokemon_1_max_hp,
      pokemon2_max_hp: pokemon_2_max_hp
    )
    pokemon_battle.save

    redirect_to pokemon_battle_path(pokemon_battle.id)
  end

  def show
    @pokemon_battle = PokemonBattle.find(params[:id])
    @damage_received = params[:damage_received].to_i
    @show_damage_received = params[:show_damage_received] == 'true'

    @current_turn = @pokemon_battle.current_turn
    @attacker     = @pokemon_battle.pokemon1
    @opponent     = @pokemon_battle.pokemon2
    @winner       = @pokemon_battle.pokemon_winner
    @loser        = @pokemon_battle.pokemon_loser

    @attacker.pokemon_player_skills.order(:id)
    @opponent.pokemon_player_skills.order(:id)
  end

  def attack
    pokemon_battle_id = params[:pokemon_battle][:pokemon_battle_id]
    skill_id = params[:pokemon_battle][:skill_id]
    current_turn = params[:current_turn].to_i

    pokemon_battle = PokemonBattle.find(pokemon_battle_id)
    skill = Skill.find(skill_id)

    attacker, opponent = determine_players(pokemon_battle_id, current_turn)

    attacker_skill = PokemonPlayerSkill.find_by(pokemon_player: attacker, skill: skill)

    # Ensure that there is a valid attacker_skill and current_pp is greater than 0
    if attacker_skill.present? && attacker_skill.current_pp > 0
      attacker_skill.update(current_pp: attacker_skill.current_pp - 1)
    end
    attacker_skill.save

    new_turn = current_turn + 1
    pokemon_battle.update(current_turn: new_turn)

    # Menghitung damage dengan calculate_damage (rumusnya ada di helper)
    damage = calculate_damage(skill.power, attacker.attack, opponent.defense)

    update_hp = [opponent.current_hp - damage, 0].max
    opponent.update(current_hp: update_hp)

    # Memeriksa apakah battle sudah selesai
    check_battle_status(pokemon_battle_id)

    redirect_to pokemon_battle_path(pokemon_battle_id, show_damage_received: true, damage_received: damage)
  end

  def history
    @pokemon_battles = PokemonBattle.page(params[:page]).per(15)
    @battle_results = []

    @pokemon_battles.each do |battle|
      winner = battle.pokemon_winner
      loser = battle.pokemon_loser

      battle_result = {
        battle_id: battle.id,
        date: battle.time,
        winner_name: winner&.name, 
        loser_name: loser&.name,
        turn: battle.current_turn,
        status: battle.status
      }

      @battle_results << battle_result
    end
  end
end

app/helpers/pokemon_battles_helper.rb
module PokemonBattlesHelper

  def determine_players(pokemon_battle_id, current_turn)
    # Mendapatkan data pemain 1 dan pemain 2 dari battle
    player_1 = PokemonBattle.find(pokemon_battle_id).pokemon1
    player_2 = PokemonBattle.find(pokemon_battle_id).pokemon2

    if current_turn.to_i.odd?
      return player_1, player_2
    else
      return player_2, player_1
    end
  end

  def calculate_damage(power, attack, defense)
    #                lvl crit                                                  stab type random
    damage = (((((2 * 1 * 1 / 5) + 2) * power * (attack / defense)) / 50) + 2) * 1.5 * 1 * 1
    damage = [damage, 1].max
    damage.to_i
  end

  def check_battle_status(pokemon_battle_id)
    pokemon_battle = PokemonBattle.find(pokemon_battle_id)

    attacker, opponent = determine_players(pokemon_battle_id, pokemon_battle.current_turn)

    if attacker.current_hp <= 0 || opponent.current_hp <= 0
      pokemon_battle.update(status: "FINISHED")

      if attacker.current_hp <= 0
        pokemon_battle.update(pokemon_winner_id: opponent.id, pokemon_loser_id: attacker.id)
      elsif opponent.current_hp <= 0
        pokemon_battle.update(pokemon_winner_id: attacker.id, pokemon_loser_id: opponent.id)
      end
    end
  end

end

app/views/pokemon_battles/history.html.erb
<h1>Battle History</h1>

<table class="table table-warning table-striped align-middle table-bordered my-4">

  <thead>
    <tr>
      <th>ID Battle</th>
      <th>Date</th>
      <th>Winner</th>
      <th>Loser</th>
      <th>Turn</th>
    </tr>
  </thead>

  <tbody>
    <% @battle_results.each do |result| %>
      <tr>
        <td><%= result[:battle_id] %></td>
        <td><%= result[:date].strftime("%B %d, %Y") %></td>
        <td>
          <% if result[:status] == "ON BATTLE" %>
            -- <%= result[:status] %> --
          <% else %>
            <%= result[:winner_name] %>
          <% end %>
        </td>
        <td>
          <% if result[:status] == "ON BATTLE" %>
            -- <%= result[:status] %> --
          <% else %>
            <%= result[:loser_name] %>
          <% end %>
        </td>
        <td><%= result[:turn] %></td>
      </tr>
    <% end %>
  </tbody>
  
</table>

<div class="d-flex justify-content-center my-4">
  <%= paginate @pokemon_battles %>
</div>

app/views/pokemon_battles/index.html.erb
<h1>Pokemon Battles</h1>

<p class="my-4">
  <%= link_to 'Create Battle', new_pokemon_battle_path, class: 'btn btn-warning mx-2' %> 
  <%= link_to 'Battle History', pokemon_battles_history_path, class: 'btn btn-secondary mx-2' %>
</p>

<table class="table table-warning table-striped align-middle table-bordered">

  <thead>
    <tr>
      <th>ID Battle</th>
      <th>Date</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @pokemon_battles.each do |battle| %>
      <tr>
        <td><%= battle.id %></td>
        <td><%= battle.time.strftime("%B %d, %Y") %></td>
        <td>
          <% if battle.status == "ON BATTLE" %>
            <strong>-- <%= battle.status %> --</strong>
          <% else %>
              <div class="badge bg-warning finished-text"><%= battle.status %></div>
          <% end %>
        </td>
        <td>
          <%= link_to 'Show', pokemon_battle_path(battle), class: 'btn-show' %>
        </td>
      </tr>
    <% end %>
  </tbody>
  
</table>

<div class="d-flex justify-content-center my-4">
  <%= paginate @pokemon_battles %>
</div>

app/views/pokemon_battles/new.html.erb
<form action="<%= pokemon_battles_path %>" accept-charset="UTF-8" method="post" class="form text-dark">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <div class="row">
        <!-- Player 1 -->
        <div class="col-6">
            <div class="mb-5">
                <h4 class="mb-3">Player 1</h4>
                <select id="pokemon-select-1" class="form-select" name="pokemon_1[pokemon_player_id]" aria-label="Default select example">
                    <option selected>Choose Pokemon</option>
                    <% @pokemons.each do |pokemon| %>
                        <option value="<%= "#{pokemon.id}-#{pokemon.max_hp}" %>"><%= pokemon.name %></option>
                    <% end %>
                </select>
            </div>
        </div>
        <!-- Player 2 -->
        <div class="col-6">
            <div class="mb-5">
                <h4 class="mb-3">Player 2</h4>
                <select id="pokemon-select-2" class="form-select" name="pokemon_2[pokemon_player_id]" aria-label="Default select example">
                    <option selected>Choose Pokemon</option>
                    <% @pokemons.each do |pokemon| %>
                        <option value="<%= "#{pokemon.id}-#{pokemon.max_hp}" %>"><%= pokemon.name %></option>
                    <% end %>
                </select>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-warning fw-bold">Start Battle</button>
</form>

app/views/pokemon_battles/show.html.erb
<h1 class="mb-4">Battle</h1>
<div class="game-container">
  <div class="row">
    <% if @pokemon_battle.status == "ON BATTLE" %>

      <div class="col">
        <div class="col">
          <div class="player-info text-dark" id="player-info">
            <h5>Player 1: <%= @pokemon_battle.pokemon1.name %></h5>
            <span><%= @pokemon_battle.pokemon1.pokedex.name %> (<%= @pokemon_battle.pokemon1.pokedex.type.name %>)</span>
            <div class="hp-bar" id="player-hp"></div>
            <p id="player-hp-text">HP: <%= @pokemon_battle.pokemon1.current_hp %></p>
          </div>
        </div>
        <div class="col">
          <div class="pokemon-container" id="attacker-attack">
            <% if @show_damage_received && @current_turn.odd? %>
              <div class="damage-text" id="attacker-damage-text">-<%= @damage_received %></div>
            <% end %>
            <img src="<%= @pokemon_battle.pokemon1.pokedex.image_url %>" alt="pokemon" class="image-battle">
          </div>
        </div>
      </div>
      <div class="col">
        <div class="col">
          <div class="player-info text-dark" id="player-info">
            <h5>Player 2: <%= @pokemon_battle.pokemon2.name %></h5>
            <span><%= @pokemon_battle.pokemon2.pokedex.name %> (<%= @pokemon_battle.pokemon2.pokedex.type.name %>)</span>
            <div class="hp-bar" id="player-hp"></div>
            <p id="player-hp-text">HP: <%= @pokemon_battle.pokemon2.current_hp %></p>
          </div>
        </div>
        <div class="col">
          <div class="pokemon-container" id="opponent-attack">
            <% if @show_damage_received && @current_turn.even? %>
              <div class="damage-text" id="opponent-damage-text">-<%= @damage_received %></div>
            <% end %>
            <img src="<%= @pokemon_battle.pokemon2.pokedex.image_url %>" alt="pokemon" class="image-battle">
          </div>
        </div>
      </div>

    <% elsif @pokemon_battle.status == "FINISHED" %>
      <div class="col">
        <div class="col">
          <div class="player-info text-dark" id="player-info">
            <h5>Player 1: <%= @pokemon_battle.pokemon1.name %></h5>
            <span><%= @pokemon_battle.pokemon1.pokedex.name %> (<%= @pokemon_battle.pokemon1.pokedex.type.name %>)</span>
            <div class="hp-bar" id="player-hp"></div>
            <p id="player-hp-text">HP: <%= @pokemon_battle.pokemon1.current_hp %></p>
          </div>
        </div>
        <div class="col">
          <div class="pokemon-container">
            <img src="<%= @pokemon_battle.pokemon1.pokedex.image_url %>" alt="pokemon" class="image-battle">
          </div>
        </div>
      </div>
      <div class="col">
        <div class="col">
          <div class="player-info text-dark" id="player-info">
            <h5>Player 2: <%= @pokemon_battle.pokemon2.name %></h5>
            <span><%= @pokemon_battle.pokemon2.pokedex.name %> (<%= @pokemon_battle.pokemon2.pokedex.type.name %>)</span>
            <div class="hp-bar" id="player-hp"></div>
            <p id="player-hp-text">HP: <%= @pokemon_battle.pokemon2.current_hp %></p>
          </div>
        </div>
        <div class="col">
          <div class="pokemon-container">
            <img src="<%= @pokemon_battle.pokemon2.pokedex.image_url %>" alt="pokemon" class="image-battle">
          </div>
        </div>
      </div>

      <% if @winner.present? %>
        <div class="box-result">
          <h2 class="text-dark">
            WINNER:<br><br>
            <%= @winner.name %>
          </h2>
        </div>
      <% end %>

    <% end %>
  </div>

  <div class="box-info">
    <% if @pokemon_battle.status == "ON BATTLE" %>
      <% if @current_turn.odd? %>
        <h3>Player 1: <%= @attacker.name %></h3>
        <% @attacker.pokemon_player_skills.each do |pokemon_skill| %>
          <form action="<%= pokemon_battles_attack_path %>" accept-charset="UTF-8" method="post">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <div class="mb-3">
              <label for="pokemon_battle_skill" class="form-label">
                <% if pokemon_skill.current_pp == 0 %>
                  <button type="submit" class="btn btn-dark disabled" onclick="playAttackerAnimation('attacker-attack')">
                    <%= pokemon_skill.skill.name %>
                    <br>
                    <%= pokemon_skill.current_pp %> / <%= pokemon_skill.skill.max_pp %>
                  </button>
                <% else %>
                  <button type="submit" class="btn btn-dark" onclick="playAttackerAnimation('attacker-attack')">
                    <%= pokemon_skill.skill.name %>
                    <br>
                    <%= pokemon_skill.current_pp %> / <%= pokemon_skill.skill.max_pp %>
                  </button>
                <% end %>
              </label>
              <input type="hidden" id="pokemon_battle_skill" name="pokemon_battle[skill_id]" value="<%= pokemon_skill.skill.id %>">
              <input type="hidden" id="current_turn" name="current_turn" value="<%= @pokemon_battle.current_turn %>">
              <input type="hidden" id="pokemon_battle" name="pokemon_battle[pokemon_battle_id]" value="<%= @pokemon_battle.id %>">
            </div>
          </form>
        <% end %>
      <% else %>
        <h3>Player 2: <%= @opponent.name %></h3>
        <% @opponent.pokemon_player_skills.each do |pokemon_skill| %>
          <form action="<%= pokemon_battles_attack_path %>" accept-charset="UTF-8" method="post">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <div class="mb-3">
              <label for="pokemon_battle_skill" class="form-label">
                <% if pokemon_skill.current_pp == 0 %>
                  <button type="submit" class="btn btn-dark disabled" onclick="playOpponentAnimation('opponent-attack')">
                    <%= pokemon_skill.skill.name %>
                    <br>
                    <%= pokemon_skill.current_pp %> / <%= pokemon_skill.skill.max_pp %>
                  </button>
                <% else %>
                  <button type="submit" class="btn btn-dark" onclick="playOpponentAnimation('opponent-attack')">
                    <%= pokemon_skill.skill.name %>
                    <br>
                    <%= pokemon_skill.current_pp %> / <%= pokemon_skill.skill.max_pp %>
                  </button>
                <% end %>
              </label>
              <input type="hidden" id="pokemon_battle_skill" name="pokemon_battle[skill_id]" value="<%= pokemon_skill.skill.id %>">
              <input type="hidden" id="current_turn" name="current_turn" value="<%= @pokemon_battle.current_turn %>">
              <input type="hidden" id="pokemon_battle" name="pokemon_battle[pokemon_battle_id]" value="<%= @pokemon_battle.id %>">
            </div>
          </form>
        <% end %>
      <% end %> 
      
    <% elsif @pokemon_battle.status == "FINISHED" %>
      <h1>Congratulations!!!</h1>
    <% end %>
  </div>

  <% if @pokemon_battle.status == "FINISHED" %>
    <table class="table table-dark table-striped align-middle table-bordered my-4">

      <thead>
        <tr>
          <th>ID Battle</th>
          <th>Winner</th>
          <th>Loser</th>
          <th>Turn</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td><%= @pokemon_battle.id %></td>
          <td><%= @winner.name %></td>
          <td><%= @loser.name %></td>
          <td><%= @current_turn %></td>
        </tr>
      </tbody>
      
    </table>
    
    <div class="d-flex justify-content-center my-4">
      <%= link_to "Back", pokemon_battles_path, class: "btn btn-secondary" %>
    </div>
  <% end %>
  
</div>

<%# animation %>
<script>
  function playAttackerAnimation(attackerAttack) {
    const attacker = document.getElementById(attackerAttack);

    attacker.classList.add('attack-animation-attacker');

    setTimeout(() => {
      attacker.classList.remove('attack-animation-attacker');
    }, 500);
  }

  function playOpponentAnimation(opponentAttack) {
    const opponent = document.getElementById(opponentAttack);

    opponent.classList.add('attack-animation-opponent');

    setTimeout(() => {
      opponent.classList.remove('attack-animation-opponent');
    }, 500);
  }
</script>