config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/about', to: 'static_pages#about'
  post '/pokemon_battles/attack',  to: 'pokemon_battles#attack'
  get  '/pokemon_battles/history', to: 'pokemon_battles#history'
  resources :pokedexes#, only: [:index, :show]
  resources :pokemons
  resources :pokemon_battles
  resources :skills
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :skills
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

  def index
    @pokemons = PokemonPlayer.page(params[:page]).per(12)
  end

  def new
    @pokedexes = Pokedex.all.order(:id)
    @skills = Skill.all
  end

  def create
    pokedex = Pokedex.find(params[:pokemon][:pokedex_id])

    # Ambil atribut dari formulir dan objek Pokedex
    pokemon_attributes = pokemon_params.merge(
      max_hp: pokedex.base_hp,
      current_hp: pokedex.base_hp,
      attack: pokedex.base_attack,
      defense: pokedex.base_defense,
      speed: pokedex.base_speed
    )

    # Buat objek PokemonPlayer dengan atribut yang telah digabungkan
    pokemon = PokemonPlayer.new(pokemon_attributes)

    if pokemon.save
      flash[:success] = "Pokemon #{pokemon.name} added to the list!"
      redirect_to pokemons_url
    else
      render 'new'
    end
  end

  def show
    @pokemon = PokemonPlayer.find(params[:id])
  end

  def destroy
    pokemon = PokemonPlayer.find(params[:id])
    pokemon.destroy
    flash[:success] = "Pokemon #{pokemon.name} deleted."
    redirect_to pokemons_url
  end

  def edit
    @pokemon = PokemonPlayer.find(params[:id])
    @pokedexes = Pokedex.all.order(:id)
    @skills = Skill.all
  end

  def update
    @pokemon = PokemonPlayer.find(params[:id])
    if @pokemon.update(pokemon_params)
      flash[:success] = 'Pokemon updated.'
      redirect_to pokemons_url
    else
      render 'edit'
    end
  end

  private

    def pokemon_params
      params.require(:pokemon).permit(:name, :pokedex_id, skill_ids: [])
    end

end

app/helpers/pokemon_helper.rb
module PokemonHelper
end

app/views/pokemons/edit.html.erb
<h1 class="mb-4">Edit Pokemon</h1>
<form action="<%= pokemon_path(@pokemon) %>" accept-charset="UTF-8" method="post" class="form text-dark">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <input type="hidden" name="_method" value="patch">
    <div class="row d-flex justify-content-center">
        <div class="col-md-8">
            <div class="mb-5">
                <label for="pokemon_name" class="form-label"><h4>Name</h4></label>
                <input type="text" class="form-control" id="pokemon_name" name="pokemon[name]" value="<%= @pokemon.name %>" placeholder="Update name" required>
            </div>
            <div class="mb-5">
                <h4>Pokedex</h4>
                <% @pokedexes.each do |pokedex| %>
                    <% if pokedex.id == @pokemon.pokedex.id %>
                        <div class="form-text mb-2">Your Pokedex is <%= pokedex.name %> (<%= pokedex.type.name %>)</div>
                    <% end %>
                <% end %>
                <select id="pokedex-select" class="form-select" name="pokemon[pokedex_id]" aria-label="Default select example">
                    <option selected>Choose your Pokedex</option>
                    <% @pokedexes.each do |pokedex| %>
                        <option value="<%= pokedex.id %>" data-type-id="<%= pokedex.type.id %>" <%= 'disabled' unless pokedex.id == @pokemon.pokedex_id %>><strong><%= pokedex.name %></strong></option>
                    <% end %>
                </select>
            </div>
            <div class="mb-5">
                
                <div id="skills-container">
                    <% @skills.each do |skill| %>
                        <div class="btn-group skill-checkbox d-none" role="group" aria-label="Skill checkbox group" data-type-id="<%= skill.type.id %>">
                            <input type="checkbox" name="pokemon[skill_ids][]" class="btn-check" id="<%= "skill_#{skill.id}" %>" value="<%= skill.id %>" autocomplete="off" <%= 'checked' if @pokemon.skill_ids.include?(skill.id) %>>
                            <label class="btn btn-outline-light mx-1 my-2" for="<%= "skill_#{skill.id}" %>">
                                <div class=" fw-bold mb-1"><%= skill.name %></div>
                                Power: <%= skill.power %>
                                <br>
                                Power Points: <%= skill.max_pp %>
                            </label>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
    
    <button type="submit" class="btn btn-warning fw-bold">UPDATE</button>
</form>

app/views/pokemons/index.html.erb
<h1>All Pokemons</h1>

<p class="my-4">
    <%= link_to 'Create Pokemon', new_pokemon_path, class: 'btn btn-warning' %> 
</p>

<div class="row">
    <% @pokemons.each do |pokemon| %>
        <div class="col pokemon-index">
            <% if pokemon.current_hp > 0 %>
                <div class="card m-3 pokemon-card">
                    <div class="card-body">
                        <a href="<%= pokemon_path(pokemon) %>" class="text-dark">
                            <img src="<%= pokemon.pokedex.image_url %>" alt="image">
                            <h5><%= pokemon.name %></h5>
                            <h6>(<%= pokemon.pokedex.name %>)</h6>
                        </a>
                    </div>
                </div>
            <% elsif pokemon.current_hp == 0 %>
                <div class="card opacity-75 m-3 pokemon-card">
                    <div class="card-body">
                        <a href="<%= pokemon_path(pokemon) %>" class="text-dark">
                            <img src="<%= pokemon.pokedex.image_url %>" alt="image">
                            <h5><%= pokemon.name %></h5>
                            <h6>(<%= pokemon.pokedex.name %>)</h6>
                        </a>
                        <%# <i>Need to heal</i> %>
                    </div>
                </div>
            <% end %>
        </div>
    <% end %>
</div>

<div class="d-flex justify-content-center my-4">
    <%= paginate @pokemons %>
</div>

app/views/pokemons/new.html.erb
<h1 class="mb-4">New Pokemon</h1>
<form action="<%= pokemons_path %>" accept-charset="UTF-8" method="post" class="form text-dark">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <div class="row d-flex justify-content-center">
        <div class="col-md-8">
            <div class="mb-5">
                <label for="pokemon_name" class="form-label"><h4>Name</h4></label>
                <input type="text" class="form-control" id="pokemon_name" name="pokemon[name]" placeholder="Your name" required>
            </div>
            <div class="mb-5">
                <h4>Pokedex</h4>
                <select id="pokedex-select" class="form-select" name="pokemon[pokedex_id]" aria-label="Default select example">
                    <option selected>Choose Pokedex</option>
                    <% @pokedexes.each do |pokedex| %>
                        <option value="<%= pokedex.id %>" data-type-id="<%= pokedex.type.id %>"><%= pokedex.name %> <%# 'disabled' if @pokemon_battle.status == "ON BATTLE" || @pokemon.current_hp == 0 %></option>
                    <% end %>
                </select>
            </div>
            <div class="mb-5">
                <h4>Choose Moves (max: 4)</h4>
                <div id="skills-container">
                    <% @skills.each do |skill| %>
                        <div class="btn-group skill-checkbox d-none" role="group" aria-label="Skill checkbox group" data-type-id="<%= skill.type.id %>">
                            <input type="checkbox" name="pokemon[skill_ids][]" class="btn-check" id="<%= "skill_#{skill.id}" %>" value="<%= skill.id %>" autocomplete="off">
                            <label class="btn btn-outline-light mx-1 my-2" id="btn-skill" for="<%= "skill_#{skill.id}" %>">
                                <div class=" fw-bold mb-1"><%= skill.name %></div>
                                Power: <%= skill.power %>
                                <br>
                                Power Points: <%= skill.max_pp %>
                            </label>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
    
    <button type="submit" class="btn btn-warning fw-bold">SUBMIT</button>
</form>

app/views/pokemons/show.html.erb
<h1 class="mb-4">Pokemon</h1>
<div class="d-flex justify-content-center">
    <div class="card" style="width: 60rem;">
        <div class="card-body">
            <div class="row d-flex justify-content-center align-items-center">
                <div class="col-lg-4">
                    <img src="<%= @pokemon.pokedex.image_url %>" alt="image" class="image-pokemon">
                    <h3><%= @pokemon.name %></h3>
                    <h5>(<%= @pokemon.pokedex.name %>)</h5>
                    <h5 class="text-uppercase">
                        <% if @pokemon.pokedex.type.name == "Grass" %>
                            <p class="badge bg-grass"><%= @pokemon.pokedex.type.name %></p>
                        <% elsif @pokemon.pokedex.type.name == "Fire" %>
                            <p class="badge bg-fire"><%= @pokemon.pokedex.type.name %></p>
                        <% elsif @pokemon.pokedex.type.name == "Water" %>
                            <p class="badge bg-water"><%= @pokemon.pokedex.type.name %></p>
                        <% elsif @pokemon.pokedex.type.name == "Normal" %>
                            <p class="badge bg-normal"><%= @pokemon.pokedex.type.name %></p>
                        <% elsif @pokemon.pokedex.type.name == "Electric" %>
                            <p class="badge bg-electric"><%= @pokemon.pokedex.type.name %></p>
                        <% elsif @pokemon.pokedex.type.name == "Bug" %>
                            <p class="badge bg-bug"><%= @pokemon.pokedex.type.name %></p>
                        <% elsif @pokemon.pokedex.type.name == "Fighting" %>
                            <p class="badge bg-fighting"><%= @pokemon.pokedex.type.name %></p>
                        <% elsif @pokemon.pokedex.type.name == "Poison" %>
                            <p class="badge bg-poison"><%= @pokemon.pokedex.type.name %></p>
                        <% elsif @pokemon.pokedex.type.name == "Flying" %>
                            <p class="badge bg-flying"><%= @pokemon.pokedex.type.name %></p>
                        <% elsif @pokemon.pokedex.type.name == "Ice" %>
                            <p class="badge bg-ice"><%= @pokemon.pokedex.type.name %></p>
                        <% elsif @pokemon.pokedex.type.name == "Ground" %>
                            <p class="badge bg-ground"><%= @pokemon.pokedex.type.name %></p>
                        <% elsif @pokemon.pokedex.type.name == "Psychic" %>
                            <p class="badge bg-psychic"><%= @pokemon.pokedex.type.name %></p>
                        <% elsif @pokemon.pokedex.type.name == "Rock" %>
                            <p class="badge bg-rock"><%= @pokemon.pokedex.type.name %></p>
                        <% elsif @pokemon.pokedex.type.name == "Ghost" %>
                            <p class="badge bg-ghost"><%= @pokemon.pokedex.type.name %></p>
                        <% elsif @pokemon.pokedex.type.name == "Dragon" %>
                            <p class="badge bg-dragon"><%= @pokemon.pokedex.type.name %></p>
                        <% elsif @pokemon.pokedex.type.name == "Fairy" %>
                            <p class="badge bg-fairy"><%= @pokemon.pokedex.type.name %></p>
                        <% else %>
                            <%= @pokemon.pokedex.type.name %>
                        <% end %>
                    </h5>
                </div>
                <div class="col-lg-6">
                    <table class="table table-warning mb-5">
                        <thead>
                            <tr>
                                <th>Max HP</th>
                                <th>Current HP</th>
                                <th>Attack</th>
                                <th>Defense</th>
                                <th>Speed</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><%= @pokemon.max_hp %></td>
                                <td><%= @pokemon.current_hp %></td>
                                <td><%= @pokemon.attack %></td>
                                <td><%= @pokemon.defense %></td>
                                <td><%= @pokemon.speed %></td>
                            </tr>
                        </tbody>
                    </table>
                    <% if (@pokemon.skills.present?) %>
                        <h5 class="mb-3">Moves:</h5>
                        <h4 class="d-flex flex-wrap justify-content-center gap-2 skills-text">
                            <% @pokemon.pokemon_player_skills.each do |skill| %>
                                <li class="badge bg-warning text-dark fw-medium">
                                    <div class="mb-2"><%= skill.skill.name %></div>
                                    <%= skill.current_pp %> / <%= skill.skill.max_pp %>
                                </li>
                            <% end %>
                        </h4>
                    <% else %>
                        <h5>No moves available.</h5>
                    <% end %>
                </div>
            </div>
            <%= link_to 'Edit', edit_pokemon_path(@pokemon), class: 'btn btn-success' %>
            <%#  link_to 'Delete', pokemon_path(@pokemon), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %> 
        </div>
    </div>
</div>