config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/about', to: 'static_pages#about'
  post '/pokemon_battles/attack',  to: 'pokemon_battles#attack'
  get  '/pokemon_battles/history', to: 'pokemon_battles#history'
  resources :pokedexes#, only: [:index, :show]
  resources :pokemons
  resources :pokemon_battles
  resources :skills
end

app/views/layouts/_footer.html.erb
<%# <footer class="content">
    <p>made by ink</p>
</footer> %>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  
  <script>
    document.addEventListener('DOMContentLoaded', function() {
        var pokedexSelect = document.getElementById('pokedex-select');
        var skillsContainer = document.getElementById('skills-container');
        var btnSkill = document.getElementById('btn-skill')
        var selectedSkills = 0;

        pokedexSelect.addEventListener('change', function() {
            var selectedTypeId = pokedexSelect.options[pokedexSelect.selectedIndex].getAttribute('data-type-id');

            // Hide all skill containers
            var skillContainers = document.querySelectorAll('.skill-checkbox');
            skillContainers.forEach(function(container) {
                container.classList.add('d-none');
            });

            // Show skill containers with the selected type
            var selectedTypeContainers = document.querySelectorAll('.skill-checkbox[data-type-id="' + selectedTypeId + '"]');
            selectedTypeContainers.forEach(function(container) {
                container.classList.remove('d-none');
            });
        });

        skillsContainer.addEventListener('change', function(event) {
            var checkbox = event.target;

            if (checkbox.checked) {
                if (selectedSkills >= 4) {
                    checkbox.checked = false;
                } else {
                    selectedSkills++;
                }
            } else {
                selectedSkills--;
            }
        });
    });
</script>

</body>
</html>

app/views/layouts/_nav.html.erb
<div class="background background-overlay">
    <nav class="navbar navbar-expand-lg" data-bs-theme="dark">
        <div class="container">
            <a class="navbar-brand" href="<%= root_path %>">Pokemon Game</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto my-2 gap-3">
                <li class="nav-item"><%= link_to "Home",    root_path,             class: "nav-link btn btn-warning" %></li>
                <li class="nav-item"><%= link_to "About",   about_path,            class: "nav-link btn btn-warning" %></li>
                <li class="nav-item"><%= link_to "Pokedex", pokedexes_path,        class: "nav-link btn btn-warning" %></li>
                <li class="nav-item"><%= link_to "Pokemon", pokemons_path,         class: "nav-link btn btn-warning" %></li>
                <li class="nav-item"><%= link_to "Battles", pokemon_battles_path,  class: "nav-link btn btn-warning" %></li>
            </ul>
        </div>
    </nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Pokemon Battle</title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <link rel="icon" type="image/ico" href="/pokeball_icon.ico">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="container content">
      <%= render 'shared/flash_messages' %> 
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>